// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/DeviceMessages.proto

package signalservice;

public final class DeviceMessages {
  private DeviceMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code signalservice.ProvisioningVersion}
   */
  public enum ProvisioningVersion
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INITIAL = 0;</code>
     */
    INITIAL(0),
    /**
     * <code>TABLET_SUPPORT = 1;</code>
     */
    TABLET_SUPPORT(1),
    ;

    /**
     * <code>CURRENT = 1;</code>
     */
    public static final ProvisioningVersion CURRENT = TABLET_SUPPORT;
    /**
     * <code>INITIAL = 0;</code>
     */
    public static final int INITIAL_VALUE = 0;
    /**
     * <code>TABLET_SUPPORT = 1;</code>
     */
    public static final int TABLET_SUPPORT_VALUE = 1;
    /**
     * <code>CURRENT = 1;</code>
     */
    public static final int CURRENT_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProvisioningVersion valueOf(int value) {
      return forNumber(value);
    }

    public static ProvisioningVersion forNumber(int value) {
      switch (value) {
        case 0: return INITIAL;
        case 1: return TABLET_SUPPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProvisioningVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProvisioningVersion> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProvisioningVersion>() {
            public ProvisioningVersion findValueByNumber(int number) {
              return ProvisioningVersion.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return signalservice.DeviceMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProvisioningVersion[] VALUES = {
      INITIAL, TABLET_SUPPORT, CURRENT, 
    };

    public static ProvisioningVersion valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProvisioningVersion(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:signalservice.ProvisioningVersion)
  }

  public interface ProvisioningUuidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisioningUuid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();
  }
  /**
   * Protobuf type {@code signalservice.ProvisioningUuid}
   */
  public  static final class ProvisioningUuid extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisioningUuid)
      ProvisioningUuidOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProvisioningUuid.newBuilder() to construct.
    private ProvisioningUuid(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProvisioningUuid() {
      uuid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisioningUuid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return signalservice.DeviceMessages.internal_static_signalservice_ProvisioningUuid_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return signalservice.DeviceMessages.internal_static_signalservice_ProvisioningUuid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(signalservice.DeviceMessages.ProvisioningUuid.class, signalservice.DeviceMessages.ProvisioningUuid.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof signalservice.DeviceMessages.ProvisioningUuid)) {
        return super.equals(obj);
      }
      signalservice.DeviceMessages.ProvisioningUuid other = (signalservice.DeviceMessages.ProvisioningUuid) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisioningUuid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(signalservice.DeviceMessages.ProvisioningUuid prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signalservice.ProvisioningUuid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisioningUuid)
        signalservice.DeviceMessages.ProvisioningUuidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisioningUuid_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisioningUuid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(signalservice.DeviceMessages.ProvisioningUuid.class, signalservice.DeviceMessages.ProvisioningUuid.Builder.class);
      }

      // Construct using signalservice.DeviceMessages.ProvisioningUuid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisioningUuid_descriptor;
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisioningUuid getDefaultInstanceForType() {
        return signalservice.DeviceMessages.ProvisioningUuid.getDefaultInstance();
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisioningUuid build() {
        signalservice.DeviceMessages.ProvisioningUuid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisioningUuid buildPartial() {
        signalservice.DeviceMessages.ProvisioningUuid result = new signalservice.DeviceMessages.ProvisioningUuid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof signalservice.DeviceMessages.ProvisioningUuid) {
          return mergeFrom((signalservice.DeviceMessages.ProvisioningUuid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(signalservice.DeviceMessages.ProvisioningUuid other) {
        if (other == signalservice.DeviceMessages.ProvisioningUuid.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        signalservice.DeviceMessages.ProvisioningUuid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (signalservice.DeviceMessages.ProvisioningUuid) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.ProvisioningUuid)
    }

    // @@protoc_insertion_point(class_scope:signalservice.ProvisioningUuid)
    private static final signalservice.DeviceMessages.ProvisioningUuid DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new signalservice.DeviceMessages.ProvisioningUuid();
    }

    public static signalservice.DeviceMessages.ProvisioningUuid getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProvisioningUuid>
        PARSER = new com.google.protobuf.AbstractParser<ProvisioningUuid>() {
      @java.lang.Override
      public ProvisioningUuid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisioningUuid(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProvisioningUuid> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisioningUuid> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public signalservice.DeviceMessages.ProvisioningUuid getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProvisionEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisionEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    boolean hasPublicKey();
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    boolean hasBody();
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code signalservice.ProvisionEnvelope}
   */
  public  static final class ProvisionEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisionEnvelope)
      ProvisionEnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProvisionEnvelope.newBuilder() to construct.
    private ProvisionEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProvisionEnvelope() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisionEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              publicKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return signalservice.DeviceMessages.internal_static_signalservice_ProvisionEnvelope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return signalservice.DeviceMessages.internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(signalservice.DeviceMessages.ProvisionEnvelope.class, signalservice.DeviceMessages.ProvisionEnvelope.Builder.class);
    }

    private int bitField0_;
    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, publicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof signalservice.DeviceMessages.ProvisionEnvelope)) {
        return super.equals(obj);
      }
      signalservice.DeviceMessages.ProvisionEnvelope other = (signalservice.DeviceMessages.ProvisionEnvelope) obj;

      boolean result = true;
      result = result && (hasPublicKey() == other.hasPublicKey());
      if (hasPublicKey()) {
        result = result && getPublicKey()
            .equals(other.getPublicKey());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPublicKey()) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKey().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisionEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(signalservice.DeviceMessages.ProvisionEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signalservice.ProvisionEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisionEnvelope)
        signalservice.DeviceMessages.ProvisionEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisionEnvelope_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(signalservice.DeviceMessages.ProvisionEnvelope.class, signalservice.DeviceMessages.ProvisionEnvelope.Builder.class);
      }

      // Construct using signalservice.DeviceMessages.ProvisionEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisionEnvelope_descriptor;
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisionEnvelope getDefaultInstanceForType() {
        return signalservice.DeviceMessages.ProvisionEnvelope.getDefaultInstance();
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisionEnvelope build() {
        signalservice.DeviceMessages.ProvisionEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisionEnvelope buildPartial() {
        signalservice.DeviceMessages.ProvisionEnvelope result = new signalservice.DeviceMessages.ProvisionEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof signalservice.DeviceMessages.ProvisionEnvelope) {
          return mergeFrom((signalservice.DeviceMessages.ProvisionEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(signalservice.DeviceMessages.ProvisionEnvelope other) {
        if (other == signalservice.DeviceMessages.ProvisionEnvelope.getDefaultInstance()) return this;
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        signalservice.DeviceMessages.ProvisionEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (signalservice.DeviceMessages.ProvisionEnvelope) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.ProvisionEnvelope)
    }

    // @@protoc_insertion_point(class_scope:signalservice.ProvisionEnvelope)
    private static final signalservice.DeviceMessages.ProvisionEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new signalservice.DeviceMessages.ProvisionEnvelope();
    }

    public static signalservice.DeviceMessages.ProvisionEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProvisionEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<ProvisionEnvelope>() {
      @java.lang.Override
      public ProvisionEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisionEnvelope(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProvisionEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisionEnvelope> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public signalservice.DeviceMessages.ProvisionEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProvisionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisionMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    boolean hasIdentityKeyPrivate();
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    com.google.protobuf.ByteString getIdentityKeyPrivate();

    /**
     * <code>optional string number = 3;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 3;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 3;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>optional string uuid = 8;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 8;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 8;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    boolean hasProvisioningCode();
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    java.lang.String getProvisioningCode();
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    com.google.protobuf.ByteString
        getProvisioningCodeBytes();

    /**
     * <code>optional string userAgent = 5;</code>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string userAgent = 5;</code>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string userAgent = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    boolean hasProfileKey();
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    com.google.protobuf.ByteString getProfileKey();

    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    boolean hasReadReceipts();
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    boolean getReadReceipts();

    /**
     * <code>optional uint32 ProvisioningVersion = 9;</code>
     */
    boolean hasProvisioningVersion();
    /**
     * <code>optional uint32 ProvisioningVersion = 9;</code>
     */
    int getProvisioningVersion();
  }
  /**
   * Protobuf type {@code signalservice.ProvisionMessage}
   */
  public  static final class ProvisionMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisionMessage)
      ProvisionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProvisionMessage.newBuilder() to construct.
    private ProvisionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProvisionMessage() {
      identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
      number_ = "";
      uuid_ = "";
      provisioningCode_ = "";
      userAgent_ = "";
      profileKey_ = com.google.protobuf.ByteString.EMPTY;
      readReceipts_ = false;
      provisioningVersion_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              bitField0_ |= 0x00000001;
              identityKeyPrivate_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              number_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              provisioningCode_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              userAgent_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              profileKey_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              readReceipts_ = input.readBool();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              uuid_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              provisioningVersion_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return signalservice.DeviceMessages.internal_static_signalservice_ProvisionMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return signalservice.DeviceMessages.internal_static_signalservice_ProvisionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(signalservice.DeviceMessages.ProvisionMessage.class, signalservice.DeviceMessages.ProvisionMessage.Builder.class);
    }

    private int bitField0_;
    public static final int IDENTITYKEYPRIVATE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString identityKeyPrivate_;
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    public boolean hasIdentityKeyPrivate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    public com.google.protobuf.ByteString getIdentityKeyPrivate() {
      return identityKeyPrivate_;
    }

    public static final int NUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object number_;
    /**
     * <code>optional string number = 3;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string number = 3;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          number_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 8;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 8;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string uuid = 8;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVISIONINGCODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object provisioningCode_;
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    public boolean hasProvisioningCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    public java.lang.String getProvisioningCode() {
      java.lang.Object ref = provisioningCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          provisioningCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProvisioningCodeBytes() {
      java.lang.Object ref = provisioningCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provisioningCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERAGENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object userAgent_;
    /**
     * <code>optional string userAgent = 5;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string userAgent = 5;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userAgent = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFILEKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString profileKey_;
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    public boolean hasProfileKey() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    public com.google.protobuf.ByteString getProfileKey() {
      return profileKey_;
    }

    public static final int READRECEIPTS_FIELD_NUMBER = 7;
    private boolean readReceipts_;
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    public boolean hasReadReceipts() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    public boolean getReadReceipts() {
      return readReceipts_;
    }

    public static final int PROVISIONINGVERSION_FIELD_NUMBER = 9;
    private int provisioningVersion_;
    /**
     * <code>optional uint32 ProvisioningVersion = 9;</code>
     */
    public boolean hasProvisioningVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 ProvisioningVersion = 9;</code>
     */
    public int getProvisioningVersion() {
      return provisioningVersion_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, identityKeyPrivate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, number_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, provisioningCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userAgent_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, profileKey_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, readReceipts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, uuid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(9, provisioningVersion_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, identityKeyPrivate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, number_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, provisioningCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userAgent_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, profileKey_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, readReceipts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, uuid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, provisioningVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof signalservice.DeviceMessages.ProvisionMessage)) {
        return super.equals(obj);
      }
      signalservice.DeviceMessages.ProvisionMessage other = (signalservice.DeviceMessages.ProvisionMessage) obj;

      boolean result = true;
      result = result && (hasIdentityKeyPrivate() == other.hasIdentityKeyPrivate());
      if (hasIdentityKeyPrivate()) {
        result = result && getIdentityKeyPrivate()
            .equals(other.getIdentityKeyPrivate());
      }
      result = result && (hasNumber() == other.hasNumber());
      if (hasNumber()) {
        result = result && getNumber()
            .equals(other.getNumber());
      }
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasProvisioningCode() == other.hasProvisioningCode());
      if (hasProvisioningCode()) {
        result = result && getProvisioningCode()
            .equals(other.getProvisioningCode());
      }
      result = result && (hasUserAgent() == other.hasUserAgent());
      if (hasUserAgent()) {
        result = result && getUserAgent()
            .equals(other.getUserAgent());
      }
      result = result && (hasProfileKey() == other.hasProfileKey());
      if (hasProfileKey()) {
        result = result && getProfileKey()
            .equals(other.getProfileKey());
      }
      result = result && (hasReadReceipts() == other.hasReadReceipts());
      if (hasReadReceipts()) {
        result = result && (getReadReceipts()
            == other.getReadReceipts());
      }
      result = result && (hasProvisioningVersion() == other.hasProvisioningVersion());
      if (hasProvisioningVersion()) {
        result = result && (getProvisioningVersion()
            == other.getProvisioningVersion());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIdentityKeyPrivate()) {
        hash = (37 * hash) + IDENTITYKEYPRIVATE_FIELD_NUMBER;
        hash = (53 * hash) + getIdentityKeyPrivate().hashCode();
      }
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
      }
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasProvisioningCode()) {
        hash = (37 * hash) + PROVISIONINGCODE_FIELD_NUMBER;
        hash = (53 * hash) + getProvisioningCode().hashCode();
      }
      if (hasUserAgent()) {
        hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
        hash = (53 * hash) + getUserAgent().hashCode();
      }
      if (hasProfileKey()) {
        hash = (37 * hash) + PROFILEKEY_FIELD_NUMBER;
        hash = (53 * hash) + getProfileKey().hashCode();
      }
      if (hasReadReceipts()) {
        hash = (37 * hash) + READRECEIPTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReadReceipts());
      }
      if (hasProvisioningVersion()) {
        hash = (37 * hash) + PROVISIONINGVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProvisioningVersion();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static signalservice.DeviceMessages.ProvisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(signalservice.DeviceMessages.ProvisionMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signalservice.ProvisionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisionMessage)
        signalservice.DeviceMessages.ProvisionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisionMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(signalservice.DeviceMessages.ProvisionMessage.class, signalservice.DeviceMessages.ProvisionMessage.Builder.class);
      }

      // Construct using signalservice.DeviceMessages.ProvisionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        provisioningCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        profileKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        readReceipts_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        provisioningVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return signalservice.DeviceMessages.internal_static_signalservice_ProvisionMessage_descriptor;
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisionMessage getDefaultInstanceForType() {
        return signalservice.DeviceMessages.ProvisionMessage.getDefaultInstance();
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisionMessage build() {
        signalservice.DeviceMessages.ProvisionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public signalservice.DeviceMessages.ProvisionMessage buildPartial() {
        signalservice.DeviceMessages.ProvisionMessage result = new signalservice.DeviceMessages.ProvisionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identityKeyPrivate_ = identityKeyPrivate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.provisioningCode_ = provisioningCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.profileKey_ = profileKey_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.readReceipts_ = readReceipts_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.provisioningVersion_ = provisioningVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof signalservice.DeviceMessages.ProvisionMessage) {
          return mergeFrom((signalservice.DeviceMessages.ProvisionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(signalservice.DeviceMessages.ProvisionMessage other) {
        if (other == signalservice.DeviceMessages.ProvisionMessage.getDefaultInstance()) return this;
        if (other.hasIdentityKeyPrivate()) {
          setIdentityKeyPrivate(other.getIdentityKeyPrivate());
        }
        if (other.hasNumber()) {
          bitField0_ |= 0x00000002;
          number_ = other.number_;
          onChanged();
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000004;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasProvisioningCode()) {
          bitField0_ |= 0x00000008;
          provisioningCode_ = other.provisioningCode_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00000010;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.hasProfileKey()) {
          setProfileKey(other.getProfileKey());
        }
        if (other.hasReadReceipts()) {
          setReadReceipts(other.getReadReceipts());
        }
        if (other.hasProvisioningVersion()) {
          setProvisioningVersion(other.getProvisioningVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        signalservice.DeviceMessages.ProvisionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (signalservice.DeviceMessages.ProvisionMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public boolean hasIdentityKeyPrivate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public com.google.protobuf.ByteString getIdentityKeyPrivate() {
        return identityKeyPrivate_;
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public Builder setIdentityKeyPrivate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        identityKeyPrivate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public Builder clearIdentityKeyPrivate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identityKeyPrivate_ = getDefaultInstance().getIdentityKeyPrivate();
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 3;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 8;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string uuid = 8;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 8;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 8;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 8;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object provisioningCode_ = "";
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public boolean hasProvisioningCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public java.lang.String getProvisioningCode() {
        java.lang.Object ref = provisioningCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            provisioningCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProvisioningCodeBytes() {
        java.lang.Object ref = provisioningCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provisioningCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public Builder setProvisioningCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        provisioningCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public Builder clearProvisioningCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        provisioningCode_ = getDefaultInstance().getProvisioningCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public Builder setProvisioningCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        provisioningCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userAgent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userAgent_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString profileKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public boolean hasProfileKey() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public com.google.protobuf.ByteString getProfileKey() {
        return profileKey_;
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public Builder setProfileKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        profileKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public Builder clearProfileKey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        profileKey_ = getDefaultInstance().getProfileKey();
        onChanged();
        return this;
      }

      private boolean readReceipts_ ;
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public boolean hasReadReceipts() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public boolean getReadReceipts() {
        return readReceipts_;
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public Builder setReadReceipts(boolean value) {
        bitField0_ |= 0x00000040;
        readReceipts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public Builder clearReadReceipts() {
        bitField0_ = (bitField0_ & ~0x00000040);
        readReceipts_ = false;
        onChanged();
        return this;
      }

      private int provisioningVersion_ ;
      /**
       * <code>optional uint32 ProvisioningVersion = 9;</code>
       */
      public boolean hasProvisioningVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 ProvisioningVersion = 9;</code>
       */
      public int getProvisioningVersion() {
        return provisioningVersion_;
      }
      /**
       * <code>optional uint32 ProvisioningVersion = 9;</code>
       */
      public Builder setProvisioningVersion(int value) {
        bitField0_ |= 0x00000080;
        provisioningVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 ProvisioningVersion = 9;</code>
       */
      public Builder clearProvisioningVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        provisioningVersion_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.ProvisionMessage)
    }

    // @@protoc_insertion_point(class_scope:signalservice.ProvisionMessage)
    private static final signalservice.DeviceMessages.ProvisionMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new signalservice.DeviceMessages.ProvisionMessage();
    }

    public static signalservice.DeviceMessages.ProvisionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProvisionMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProvisionMessage>() {
      @java.lang.Override
      public ProvisionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisionMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProvisionMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisionMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public signalservice.DeviceMessages.ProvisionMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_ProvisioningUuid_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_ProvisioningUuid_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_ProvisionEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_ProvisionMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_ProvisionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protos/DeviceMessages.proto\022\rsignalser" +
      "vice\" \n\020ProvisioningUuid\022\014\n\004uuid\030\001 \001(\t\"4" +
      "\n\021ProvisionEnvelope\022\021\n\tpublicKey\030\001 \001(\014\022\014" +
      "\n\004body\030\002 \001(\014\"\300\001\n\020ProvisionMessage\022\032\n\022ide" +
      "ntityKeyPrivate\030\002 \001(\014\022\016\n\006number\030\003 \001(\t\022\014\n" +
      "\004uuid\030\010 \001(\t\022\030\n\020provisioningCode\030\004 \001(\t\022\021\n" +
      "\tuserAgent\030\005 \001(\t\022\022\n\nprofileKey\030\006 \001(\014\022\024\n\014" +
      "readReceipts\030\007 \001(\010\022\033\n\023ProvisioningVersio" +
      "n\030\t \001(\r*G\n\023ProvisioningVersion\022\013\n\007INITIA" +
      "L\020\000\022\022\n\016TABLET_SUPPORT\020\001\022\013\n\007CURRENT\020\001\032\002\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_signalservice_ProvisioningUuid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signalservice_ProvisioningUuid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_ProvisioningUuid_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_signalservice_ProvisionEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_ProvisionEnvelope_descriptor,
        new java.lang.String[] { "PublicKey", "Body", });
    internal_static_signalservice_ProvisionMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_signalservice_ProvisionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_ProvisionMessage_descriptor,
        new java.lang.String[] { "IdentityKeyPrivate", "Number", "Uuid", "ProvisioningCode", "UserAgent", "ProfileKey", "ReadReceipts", "ProvisioningVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
